### ISSUE TITLE
Better Engima

### ISSUE THREAD

**Issue by sylv256** [DuvetMC/IntermediaryChaos#1]
We should be using our version of Engima. We can host it on `maven.concern.i.ng` until we get an official maven server.

**Comment by sschr15** [comment]
Why not just PR our changes upstream?

**Comment by sylv256** [comment]
We should probably do that.

**Comment by sylv256** [comment]
https://github.com/QuiltMC/enigma/pull/33

**Comment by eristhea** [comment]
@SylvKT  @sschr15 all prs from the duvet team have been merged upstream!
